(function() {
  window.addEventListener('load', function() {
    var classes = [
		'bg-black aqua',
		'bg-black blue',
		'bg-black lime',
		'bg-black teal',
		'bg-black olive',
		'bg-black green',
		'bg-black red',
		'bg-black orange',
		'bg-black purple',
		'bg-black yellow',
		'bg-black fuchsia',
		'bg-black gray',
		'bg-black white',
		'bg-black silver',
		'bg-white blue',
		'bg-white navy',
		'bg-white olive',
		'bg-white red',
		'bg-white maroon',
		'bg-white purple',
		'bg-white fuchsia',
		'bg-white black',
		'bg-silver blue',
		'bg-silver navy',
		'bg-silver maroon',
		'bg-silver fucshia',
		'bg-silver black',
		'bg-gray navy',
		'bg-gray maroon',
		'bg-gray black',
		'bg-fuchsia navy',
		'bg-fuchsia white',
		'bg-fuchsia black',
		'bg-yellow purple',
		'bg-yellow maroon',
		'bg-yellow navy',
		'bg-yellow blue',
		'bg-yellow black',
		'bg-purple lime',
		'bg-purple silver',
		'bg-purple black',
		'bg-purple white',
		'bg-purple yellow',
		'bg-orange maroon',
		'bg-orange navy',
		'bg-orange black',
		'bg-maroon lime',
		'bg-maroon aqua',
		'bg-maroon green',
		'bg-maroon orange',
		'bg-maroon yellow',
		'bg-maroon gray',
		'bg-maroon white',
		'bg-maroon silver',
		'bg-red navy',
		'bg-red white',
		'bg-red black',
		'bg-aqua navy',
		'bg-aqua maroon',
		'bg-aqua fuchsia',
		'bg-aqua black',
		'bg-blue lime',
		'bg-blue navy',
		'bg-blue yellow',
		'bg-blue white',
		'bg-blue black',
		'bg-blue silver',
		'bg-navy blue',
		'bg-navy aqua',
		'bg-navy olive',
		'bg-navy green',
		'bg-navy lime',
		'bg-navy red',
		'bg-navy orange',
		'bg-navy yellow',
		'bg-navy fuchsia',
		'bg-navy gray',
		'bg-navy silver',
		'bg-navy white',
		'bg-teal navy',
		'bg-teal maroon',
		'bg-teal black',
		'bg-lime blue',
		'bg-lime navy',
		'bg-lime maroon',
		'bg-lime fuchsia',
		'bg-lime black',
		'bg-olive navy',
		'bg-olive white',
		'bg-olive black',
		'bg-green navy',
		'bg-green black',
		'bg-green maroon'
    ];

    var elements = document.querySelectorAll(".colors-js");
    for (var i = 0; i < elements.length; i++) {
      var selectedClasses = classes[Math.floor(Math.random() * classes.length)].split(' ');
      for (var c = 0; c < selectedClasses.length; c++) {
        elements[i].classList.add(selectedClasses[c]); //Can only add one at a time!
      }
    }
  });
})();
